### ISSUE TITLE
Add wiki so I can add a Maven pom.xml

### ISSUE THREAD

**Issue by sarnobat** [TheMagican/webdav-embedded-server#1]
Thank you very much for this repo, it made things much easier for me using Milton.

It took me a while to get it working using Maven (I'm not familiar with Gradle). I'd like to share my pom.xml that works to save others time. I was hoping there was a wiki I could put it on, but perhaps it's not enabled for this repo. Would you consider adding one?

Here is my pom.xml:

```
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>webdav-embedded-server</groupId>
	<artifactId>webdav-embedded-server</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<repositories>
		<repository>
			<id>milton-repo</id>
			<url>http://dl.bintray.com/milton/Milton</url>
		</repository>
	</repositories>
	<build>
		<plugins>

			<plugin>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.2</version>
				<configuration>
					<source>1.8</source>
					<target>1.8</target>
				</configuration>
			</plugin>

		</plugins>

	</build>
	<dependencies>

		<dependency>
			<groupId>org.apache.commons</groupId>
			<artifactId>commons-lang3</artifactId>
			<version>3.7</version>
		</dependency>

		<dependency>
			<groupId>org.eclipse.jetty</groupId>
			<artifactId>jetty-server</artifactId>
			<version>9.0.0.v20130308</version>
		</dependency>


		<dependency>
			<groupId>com.beust</groupId>
			<artifactId>jcommander</artifactId>
			<version>1.72</version>
		</dependency>

		<dependency>
			<groupId>io.milton</groupId>
			<artifactId>milton-server-ce</artifactId>
			<version>2.7.2.4</version>
		</dependency>

	</dependencies>
</project>
```

**Comment by atetzner** [comment]
Thanks for your suggestion!
I have enabled the Wiki for the repository. If you like, you can add your pom.xml to the Wiki yourself. Otherwise I will do that today evening, together with a more complete example how to use the library with gradle.

**Comment by atetzner** [comment]
Done

**Comment by atetzner** [comment]
I misinterpreted your code from above: I thought it would be a `pom.xml` to use the `webdav-embedded-server` in another project as an external library. As I wrote, I added wiki pages for that.

But instead, as I now realised, your `pom.xml` is code for _building this project with maven_. Sorry for that error. So in this case: The build-system of this library is gradle and I think it would be confusing to provide a second way to build the library. Besides that, I don't see any requirement to build the library yourself, as I provide compiled versions of the library on JCenter. I hope the wiki pages I added clarify that you don't need to know gradle to use this library in your own project.

If you wanted to use the webdav-embedded-server in its standalone version: I additionally added the compiled version to the [Release page](https://github.com/TheMagican/webdav-embedded-server/releases) for easy download without the need to compile it.

**Comment by sarnobat** [comment]
Oh I didn't realize there was a precompiled release. In that case yes I don't want to confuse your users by adding such samples.

Maybe some instructions on building with Gradle building might be useful. But otherwise everything's fine.

**Comment by sarnobat** [comment]
I should open a new issue for this, but any chance you could release a jar-with-dependencies or uber-jar? I'd like to use the server as-is, rather than as a library but getting all the dependencies and supplying them at the command line is a bit of work.

**Comment by atetzner** [comment]
I created #2 for this
