### ISSUE TITLE
Update to newer milton releases?

### ISSUE THREAD

**Issue by laeubi** [TheMagican/webdav-embedded-server#5]
It seems that there is already milton 3 release and most of the dependencies of this project are gone, would it be possible to upgrade to the most recent release?

**Comment by laeubi** [comment]
@atetzner I was able to check this with more recent milton release an it only requires a minor change in `MiltonFileResource#refreshLock` but I can't even get the gradle build working with a recent java release. Would you be so kind of upgrading the milton and grade release and perform a new release of this useful library?

**Comment by atetzner** [comment]
I have updated dependencies to recent ones. `master` now uses `3.0.0.180` of Milton.

To get the changes now, you can download recent build artifacts from the GitHub Actions run [here](https://github.com/atetzner/webdav-embedded-server/actions?query=branch%3Amaster). I will publish releases to some repo with #7 and close this issue as resolved.

Feel free to reopen the issue if necessary.

**Comment by laeubi** [comment]
Great! By the way before "real" deploymento to central, there is a stagin-repo created so let me know when thats ready and I'll try to perform a "prerelease" test :+1:
