### ISSUE TITLE
Deploy to maven central

### ISSUE THREAD

**Issue by laeubi** [TheMagican/webdav-embedded-server#7]
Currently the library is deployed to JCenter.

It would be great if it would be deployed to maven central directly instead.

For this one can request a project group-id here https://central.sonatype.org/publish/

**Comment by atetzner** [comment]
Seems that the hurdle to publish to Maven Central is still high compared to the time when I decided to publish to JCenter. I think I will start with publishing to GitHub Packages and later see if I have time to also publish to Maven Central.

**Comment by laeubi** [comment]
> Seems that the hurdle to publish to Maven Central is still high compared to the time when I decided to publish to JCenter

Can you explain the problem? I recently did this and it was simply a nobrainer:

1. Create a project ticket and choose as group ID `io.github.<yourusername>` https://issues.sonatype.org/secure/CreateIssue.jspa?pid=10134&issuetype=21
2. Create a repository and name it `OSSRH-<TICKETNUMBER>`

The rest should be automatic.

**Comment by atetzner** [comment]
I am currently using `de.bitinsomnia` as group ID for the artifacts this induces two problems:
1. To use this group ID, I need to add a TXT record to my DNS settings for verification. This is no problem in general but just a bit of pain ...
2. The domain of my personal website is `bit-insomnia.de`. I removed the dash from the group ID to have more conformal names. Don't know if they will allow me to use `de.bitinsomnia` at all ...

So potentially I need to change the group ID of the lib ...

Another hurdle that was at least in place when I started this repo was, that I need to sign my JARs. Is this also the case at the moment?

For now, I have released `v0.2.0` and published it to GitHub Packages - see [here](https://github.com/atetzner/webdav-embedded-server#usage) for more information. I will see if I have time to also publish to Maven Central.

**Comment by laeubi** [comment]
> So potentially I need to change the group ID of the lib ...

Would this be a real issue? You could even create a github organization called `bitinsomnia` then the group ID would be `io.github.bitinsomnia`, you can then create even a redirect to your "real" website from `bitinsomnia.github.io` to `bit-insomnia.de` another choice of course would be to register the domain `bitinsomnia.de` there is currently an offer for 0,08 € / month in the first year https://order.df.eu/germany/bestellung.php?action=showcart&globalaction=hosting&lookup_domain=bitinsomnia

> Another hurdle that was at least in place when I started this repo was, that I need to sign my JARs. Is this also the case at the moment?

Yes you need to (PGP) sign the jar but thats not that hard as it sound

1. generate PGPG key pair
2. Upload the public part to hkp://pgp.mit.edu
3. enable the [maven-gpg-plugin](http://maven.apache.org/plugins/maven-gpg-plugin/)

Here is a more complete one https://blog.sonatype.com/2010/01/how-to-generate-pgp-signatures-with-maven/

> For now, I have released `v0.2.0` and published it to GitHub Packages - see [here](https://github.com/atetzner/webdav-embedded-server#usage) for more information. I will see if I have time to also publish to Maven Central.

I'll try that out, maven central is just more "standard" and requires less setup for the usual maven builds (maybe this will change in the future)... but it is of course your choice :-)

**Comment by laeubi** [comment]
I just noticed that the following page could need an update:

https://github.com/atetzner/webdav-embedded-server/wiki/How-To-use-with-Maven

maybe you want to add example configuration how to access the Github repository? It seems one needs to always authenticate to use it even fro read-only?

**Comment by atetzner** [comment]
I didn't know that one needs to authenticate to GH packages just for usage / download of a package. I don't know what the reason for this was, but IMHO that's not very user friendly 😞 

In this case, GH packages isn't a good solution and I will publish the artifact also to Maven Central. I hope to find time to implement it soon ...

**Comment by atetzner** [comment]
Sorry for the delay. I just published version `0.2.1` to Maven Central.

At the moment I can't find it using https://search.maven.org/ or resolve the dependency in a test Gradle build. Do you know how long it takes between publishing something to Maven Central and when it is actually accessible? Or did something go wrong with the publishing?

**Comment by laeubi** [comment]
It usually takes up to an hour to appear on maven central not sure about the maven search, but you can check with:

`https://repo1.maven.org/maven2/<groupid replacing dot by />/`

For it do be deployed you have to do following steps:

1. deploy the release
2. then login to the sonatype nexus (https://oss.sonatype.org/#stagingRepositories) and go to staging repos, then you can review/test/... with the staging repo
3. If you are fine close the staging repository, some checks will be performed, so you can press "refresh" after a few seconds to see the result
4. then you can select the repro and choose "release"

Then is usually takes a few minutes until it show up at https://repo1.maven.org/maven2/ and you can use it.

**Comment by laeubi** [comment]
@atetzner as I cant find it yet on central I assume you have not promoted the repository, do you like to check this?

**Comment by atetzner** [comment]
I am sorry for the delay as I hadn't time to look into the problem for personal reasons.

I am pretty sure, that I have now released the library correctly and it should be available on Maven Central within the next hours. I can already see the dependency in "Public Repositories" of https://s01.oss.sonatype.org - so it should just be a matter of time ...

**Comment by laeubi** [comment]
Great, many thanks and no problem with the delay!

**Comment by atetzner** [comment]
The Library is now available in Maven Central: https://search.maven.org/search?q=g:io.github.atetzner
